### ISSUE TITLE
composer bug

### ISSUE THREAD

**Issue by xima-wla** [ext-news/news_subheadline#1]
Hi Georg Ringer,

I use composer, use either "georgringer/news-subheadline":"1.0.* or "typo3-ter/news-subheadline":"1.0.*

But I get an error message: "The requested package georgringer/news-subheadline could not be found in any version, there may be a typo in the package name."

Composer URL: https://composer.typo3.org

Greetings,
Wiebke

**Comment by georgringer** [comment]
the extension is not in the ter but now on packagist https://packagist.org/packages/georgringer/news-subheadline
