### ISSUE TITLE
news_subheadline via composer

### ISSUE THREAD

**Issue by xima-wla** [ext-news/news_subheadline#2]
Hello Georg Ringer,

I loaded news_subdheadline via composer from packagist.
But when I activate the extension I get an error:

Required extension "news":
The extension news is installed in version 6.1.1 but needed in version 3.2.5 - 4.9.99

Can I use this extension with news 6.1.1?

news  6.1.1
TYPO3 7.6

Thanks,
Wiebke

**Comment by georgringer** [comment]
fixed

**Comment by xima-wla** [comment]
Please update your new version on packagist.

Thx,
Wiebke
